<a href="https://colab.research.google.com/github/AbhinavKumar07/C129/blob/main/C129.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
!git clone https://github.com/procodingclass/PRO-NASA-Exoplanet-Scraped-Data

fatal: destination path 'PRO-NASA-Exoplanet-Scraped-Data' already exists and is not an empty directory.

In [15]:
import pandas as pd

planet_df_1 = pd.read_csv('/content/PRO-NASA-Exoplanet-Scraped-Data/updated_scraped_data.csv') #Main page

new_planet_df_1 = pd.read_csv('/content/PRO-NASA-Exoplanet-Scraped-Data/new_scraped_data.csv') #Other info inside specific page

planet_df_1.head(20)

,id,name,light_years_from_earth,planet_mass,stellar_magnitude,discovery_date,hyperlink
0,0,11 Comae Berenices b,304.0,19.4 Jupiters,4.72307,2007,https://exoplanets.nasa.gov/exoplanet-catalog/...
1,1,11 Ursae Minoris b,409.0,14.74 Jupiters,5.01300,2009,https://exoplanets.nasa.gov/exoplanet-catalog/...
2,2,14 Andromedae b,246.0,4.8 Jupiters,5.23133,2008,https://exoplanets.nasa.gov/exoplanet-catalog/...
3,3,14 Herculis b,58.0,4.66 Jupiters,6.61935,2002,https://exoplanets.nasa.gov/exoplanet-catalog/...
4,4,16 Cygni B b,69.0,1.78 Jupiters,6.21500,1996,https://exoplanets.nasa.gov/exoplanet-catalog/...
5,5,17 Scorpii b,408.0,4.32 Jupiters,5.22606,2020,https://exoplanets.nasa.gov/exoplanet-catalog/...
6,6,18 Delphini b,249.0,10.3 Jupiters,5.51048,2008,https://exoplanets.nasa.gov/exoplanet-catalog/...
7,7,1RXS J160929.1-210524 b,454.0,8 Jupiters,12.61800,2008,https://exoplanets.nasa.gov/exoplanet-catalog/...
8,8,24 Bootis b,313.0,0.91 Jupiters,5.59000,2018,https://exoplanets.nasa.gov/exoplanet-catalog/...
9,9,24 Sextantis b,235.0,1.99 Jupiters,6.45350,2010,https://exoplanets.nasa.gov/exoplanet-catalog/...
10,10,24 Sextantis c,235.0,0.86 Jupiters,6.45350,2010,https://exoplanets.nasa.gov/exoplanet-catalog/...
11,11,2M0437 b,419.0,4 Jupiters,16.18600,2021,https://exoplanets.nasa.gov/exoplanet-catalog/...
12,12,2MASS J01033563-5515561 AB b,154.0,13 Jupiters,15.78800,2013,https://exoplanets.nasa.gov/exoplanet-catalog/...
13,13,2MASS J01225093-2439505 b,110.0,24.5 Jupiters,14.24400,2013,https://exoplanets.nasa.gov/exoplanet-catalog/...
14,14,2MASS J02192210-3925225 b,131.0,13.9 Jupiters,15.01230,2015,https://exoplanets.nasa.gov/exoplanet-catalog/...
15,15,2MASS J04414489+2301513 b,393.0,7.5 Jupiters,18.96680,2010,https://exoplanets.nasa.gov/exoplanet-catalog/...
16,16,2MASS J12073346-3932539 b,210.0,5 Jupiters,20.15000,2004,https://exoplanets.nasa.gov/exoplanet-catalog/...
17,17,2MASS J19383260+4603591 b,1293.0,1.9 Jupiters,12.65100,2015,https://exoplanets.nasa.gov/exoplanet-catalog/...
18,18,2MASS J21402931+1625183 A b,108.0,20.95 Jupiters,17.39610,2009,https://exoplanets.nasa.gov/exoplanet-catalog/...
19,19,2MASS J22362452+4751425 b,227.0,12.5 Jupiters,12.36800,2016,https://exoplanets.nasa.gov/exoplanet-catalog/...

In [16]:
new_planet_df_1.head(10)

,id,planet_type,discovery_date,mass,planet_radius,orbital_radius,orbital_period,eccentricity,detection_method
0,0,Gas Giant,2007,19.4 Jupiters,1.08 x Jupiter,1.29 AU,326 days,0.23,NaN
1,1,Gas Giant,2009,14.74 Jupiters,1.09 x Jupiter,1.53 AU,1.4 years,0.08,NaN
2,2,Gas Giant,2008,4.8 Jupiters,1.15 x Jupiter,0.83 AU,185.8 days,0.0,NaN
3,3,Gas Giant,2002,4.66 Jupiters,1.15 x Jupiter,2.93 AU,4.9 years,0.37,NaN
4,4,Gas Giant,1996,1.78 Jupiters,1.2 x Jupiter,1.66 AU,2.2 years,0.68,NaN
5,5,Gas Giant,2020,4.32 Jupiters,1.15 x Jupiter,1.45 AU,1.6 years,0.06,NaN
6,6,Gas Giant,2008,10.3 Jupiters,1.11 x Jupiter,2.6 AU,2.7 years,0.08,NaN
7,7,Gas Giant,2008,8 Jupiters,1.664 x Jupiter,330.0 AU,6505.9 years,0.0,NaN
8,8,Gas Giant,2018,0.91 Jupiters,1.24 x Jupiter,0.19 AU,30.4 days,0.04,NaN
9,9,Gas Giant,2010,1.99 Jupiters,1.19 x Jupiter,1.333 AU,452.8 days,0.09,NaN

In [17]:
#new_planet_df_1.drop(columns = ['detection_method' , 'mass'] , inplace=True) #Removes columns
new_planet_df_1.head()

,id,planet_type,discovery_date,mass,planet_radius,orbital_radius,orbital_period,eccentricity,detection_method
0,0,Gas Giant,2007,19.4 Jupiters,1.08 x Jupiter,1.29 AU,326 days,0.23,NaN
1,1,Gas Giant,2009,14.74 Jupiters,1.09 x Jupiter,1.53 AU,1.4 years,0.08,NaN
2,2,Gas Giant,2008,4.8 Jupiters,1.15 x Jupiter,0.83 AU,185.8 days,0.0,NaN
3,3,Gas Giant,2002,4.66 Jupiters,1.15 x Jupiter,2.93 AU,4.9 years,0.37,NaN
4,4,Gas Giant,1996,1.78 Jupiters,1.2 x Jupiter,1.66 AU,2.2 years,0.68,NaN

In [18]:
headers = ["name" , "light_years_from_earth" , "planet_mass" , "stellar_magnitude" , "discovery_date" , "hyperlink" , "planet_type" , "planet_radius" , "orbital_radius" , "orbital_period", "eccentricity" , "detection_method"]

final_planet_df = pd.DataFrame(columns = headers)
final_planet_df = pd.merge(planet_df_1 , new_planet_df_1)
final_planet_df.head()

,id,name,light_years_from_earth,planet_mass,stellar_magnitude,discovery_date,hyperlink,planet_type,mass,planet_radius,orbital_radius,orbital_period,eccentricity,detection_method
0,0,11 Comae Berenices b,304.0,19.4 Jupiters,4.72307,2007,https://exoplanets.nasa.gov/exoplanet-catalog/...,Gas Giant,19.4 Jupiters,1.08 x Jupiter,1.29 AU,326 days,0.23,NaN
1,1,11 Ursae Minoris b,409.0,14.74 Jupiters,5.01300,2009,https://exoplanets.nasa.gov/exoplanet-catalog/...,Gas Giant,14.74 Jupiters,1.09 x Jupiter,1.53 AU,1.4 years,0.08,NaN
2,2,14 Andromedae b,246.0,4.8 Jupiters,5.23133,2008,https://exoplanets.nasa.gov/exoplanet-catalog/...,Gas Giant,4.8 Jupiters,1.15 x Jupiter,0.83 AU,185.8 days,0.0,NaN
3,3,14 Herculis b,58.0,4.66 Jupiters,6.61935,2002,https://exoplanets.nasa.gov/exoplanet-catalog/...,Gas Giant,4.66 Jupiters,1.15 x Jupiter,2.93 AU,4.9 years,0.37,NaN
4,4,16 Cygni B b,69.0,1.78 Jupiters,6.21500,1996,https://exoplanets.nasa.gov/exoplanet-catalog/...,Gas Giant,1.78 Jupiters,1.2 x Jupiter,1.66 AU,2.2 years,0.68,NaN

In [20]:
final_planet_df.shape

(5009, 14)

In [23]:
final_planet_df.to_csv('final_scrapped_data.csv')
from google.colab import files
files.download('final_scrapped_data.csv')

In [24]:
a_planet_df = pd.read_csv('/content/PRO-NASA-Exoplanet-Scraped-Data/PSCompPars.csv')
a_planet_df.head(10)

,id,pl_name,hostname,sy_snum,sy_pnum,discoverymethod,disc_year,disc_facility,pl_controv_flag,pl_orbper,...,sy_disterr2,sy_vmag,sy_vmagerr1,sy_vmagerr2,sy_kmag,sy_kmagerr1,sy_kmagerr2,sy_gaiamag,sy_gaiamagerr1,sy_gaiamagerr2
0,0,11 Com b,11 Com,2,1,Radial Velocity,2007,Xinglong Station,0,326.03000,...,-1.92380,4.72307,0.023,-0.023,2.282,0.346,-0.346,4.44038,0.003848,-0.003848
1,1,11 UMi b,11 UMi,1,1,Radial Velocity,2009,Thueringer Landessternwarte Tautenburg,0,516.21997,...,-1.97650,5.01300,0.005,-0.005,1.939,0.270,-0.270,4.56216,0.003903,-0.003903
2,2,14 And b,14 And,1,1,Radial Velocity,2008,Okayama Astrophysical Observatory,0,185.84000,...,-0.71400,5.23133,0.023,-0.023,2.331,0.240,-0.240,4.91781,0.002826,-0.002826
3,3,14 Her b,14 Her,1,2,Radial Velocity,2002,W. M. Keck Observatory,0,1773.40002,...,-0.00730,6.61935,0.023,-0.023,4.714,0.016,-0.016,6.38300,0.000351,-0.000351
4,4,16 Cyg B b,16 Cyg B,3,1,Radial Velocity,1996,Multiple Observatories,0,798.50000,...,-0.01110,6.21500,0.016,-0.016,4.651,0.016,-0.016,6.06428,0.000603,-0.000603
5,5,17 Sco b,17 Sco,1,1,Radial Velocity,2020,Lick Observatory,0,578.38000,...,-2.59000,5.22606,0.023,-0.023,2.094,0.244,-0.244,4.75429,0.005055,-0.005055
6,6,18 Del b,18 Del,2,1,Radial Velocity,2008,Okayama Astrophysical Observatory,0,993.30000,...,-0.62170,5.51048,0.023,-0.023,3.366,0.204,-0.204,5.27476,0.002654,-0.002654
7,7,1RXS J160929.1-210524 b,1RXS J160929.1-210524,1,1,Imaging,2008,Gemini Observatory,0,NaN,...,-1.30700,12.61800,0.069,-0.069,8.916,0.021,-0.021,12.05720,0.002275,-0.002275
8,8,24 Boo b,24 Boo,1,1,Radial Velocity,2018,Okayama Astrophysical Observatory,0,30.35060,...,-0.63685,5.59000,0.001,-0.001,3.159,0.280,-0.280,5.33390,0.002000,-0.002000
9,9,24 Sex b,24 Sex,1,2,Radial Velocity,2010,Lick Observatory,0,452.80000,...,-0.67280,6.45350,0.023,-0.023,4.285,0.016,-0.016,6.20374,0.000498,-0.000498

In [25]:
a_planet_df = a_planet_df.sort_values('pl_name')
a_planet_df.tail(20)

,id,pl_name,hostname,sy_snum,sy_pnum,discoverymethod,disc_year,disc_facility,pl_controv_flag,pl_orbper,...,sy_disterr2,sy_vmag,sy_vmagerr1,sy_vmagerr2,sy_kmag,sy_kmagerr1,sy_kmagerr2,sy_gaiamag,sy_gaiamagerr1,sy_gaiamagerr2
4989,4989,nu Oph b,nu Oph,1,2,Radial Velocity,2012,Okayama Astrophysical Observatory,0,530.210000,...,-1.73313,3.31216,0.023,-0.023,1.225,0.306,-0.306,3.09653,0.016416,-0.016416
4990,4990,nu Oph c,nu Oph,1,2,Radial Velocity,2012,Okayama Astrophysical Observatory,0,3184.830000,...,-1.73313,3.31216,0.023,-0.023,1.225,0.306,-0.306,3.09653,0.016416,-0.016416
4991,4991,ome Ser b,ome Ser,2,1,Radial Velocity,2013,Okayama Astrophysical Observatory,0,277.020000,...,-0.79490,5.21644,0.023,-0.023,2.929,0.224,-0.224,4.92833,0.002338,-0.002338
4992,4992,omi CrB b,omi CrB,1,1,Radial Velocity,2012,Okayama Astrophysical Observatory,0,187.830000,...,-0.55330,5.50520,0.023,-0.023,2.934,0.322,-0.322,5.22055,0.001743,-0.001743
4993,4993,omi UMa b,omi UMa,2,1,Radial Velocity,2012,Okayama Astrophysical Observatory,0,1630.000000,...,-2.06076,3.35214,0.023,-0.023,1.339,0.202,-0.202,3.14432,0.000786,-0.000786
4994,4994,pi Men c,HD 39091,1,2,Transit,2018,Transiting Exoplanet Survey Satellite (TESS),0,6.267900,...,-0.02260,5.65000,0.030,-0.030,4.241,0.027,-0.027,5.51280,0.001946,-0.001946
4995,4995,psi 1 Dra B b,psi 1 Dra B,3,1,Radial Velocity,2015,McDonald Observatory,0,3117.000000,...,-0.02580,5.80800,0.015,-0.015,4.527,0.023,-0.023,5.64766,0.001221,-0.001221
4996,4996,rho CrB b,rho CrB,1,2,Radial Velocity,1997,Fred Lawrence Whipple Observatory,1,39.845800,...,-0.02400,5.40816,0.023,-0.023,3.857,0.036,-0.036,5.24167,0.002174,-0.002174
4997,4997,rho CrB c,rho CrB,1,2,Radial Velocity,2016,Multiple Observatories,0,102.540000,...,-0.02400,5.40816,0.023,-0.023,3.857,0.036,-0.036,5.24167,0.002174,-0.002174
4998,4998,tau Boo b,tau Boo,2,1,Radial Velocity,1996,Lick Observatory,0,3.312457,...,-0.08380,4.48635,0.023,-0.023,3.507,0.348,-0.348,4.36617,0.006422,-0.006422
4999,4999,tau Cet e,tau Cet,1,4,Radial Velocity,2017,Multiple Observatories,0,162.870000,...,-0.00675,3.49607,0.023,-0.023,1.794,0.274,-0.274,3.24854,0.010399,-0.010399
5000,5000,tau Cet f,tau Cet,1,4,Radial Velocity,2017,Multiple Observatories,0,636.130000,...,-0.00675,3.49607,0.023,-0.023,1.794,0.274,-0.274,3.24854,0.010399,-0.010399
5001,5001,tau Cet g,tau Cet,1,4,Radial Velocity,2017,Multiple Observatories,0,20.000000,...,-0.00675,3.49607,0.023,-0.023,1.794,0.274,-0.274,3.24854,0.010399,-0.010399
5002,5002,tau Cet h,tau Cet,1,4,Radial Velocity,2017,Multiple Observatories,0,49.410000,...,-0.00675,3.49607,0.023,-0.023,1.794,0.274,-0.274,3.24854,0.010399,-0.010399
5003,5003,tau Gem b,tau Gem,1,1,Radial Velocity,2013,Lick Observatory,0,305.500000,...,-3.95900,4.37799,0.023,-0.023,1.681,0.254,-0.254,4.03996,0.006709,-0.006709
5004,5004,ups And b,ups And,2,3,Radial Velocity,1996,Lick Observatory,0,4.617033,...,-0.06290,4.09565,0.023,-0.023,2.859,0.274,-0.274,3.98687,0.008937,-0.008937
5005,5005,ups And c,ups And,2,3,Radial Velocity,1999,Multiple Observatories,0,241.258000,...,-0.06290,4.09565,0.023,-0.023,2.859,0.274,-0.274,3.98687,0.008937,-0.008937
5006,5006,ups And d,ups And,2,3,Radial Velocity,1999,Multiple Observatories,0,1276.460000,...,-0.06290,4.09565,0.023,-0.023,2.859,0.274,-0.274,3.98687,0.008937,-0.008937
5007,5007,ups Leo b,ups Leo,1,1,Radial Velocity,2021,Okayama Astrophysical Observatory,0,385.200000,...,-0.89630,4.30490,0.023,-0.023,2.184,0.248,-0.248,4.03040,0.008513,-0.008513
5008,5008,xi Aql b,xi Aql,1,1,Radial Velocity,2007,Okayama Astrophysical Observatory,0,136.750000,...,-0.55975,4.70964,0.023,-0.023,2.171,0.220,-0.220,4.42501,0.003837,-0.003837

In [26]:
merge_planet_df = pd.merge(final_planet_df , a_planet_df , on='id')
merge_planet_df.shape

(5009, 98)

In [27]:
merge_planet_df.columns

Index(['id', 'name', 'light_years_from_earth', 'planet_mass',
       'stellar_magnitude', 'discovery_date', 'hyperlink', 'planet_type',
       'mass', 'planet_radius', 'orbital_radius', 'orbital_period',
       'eccentricity', 'detection_method', 'pl_name', 'hostname', 'sy_snum',
       'sy_pnum', 'discoverymethod', 'disc_year', 'disc_facility',
       'pl_controv_flag', 'pl_orbper', 'pl_orbpererr1', 'pl_orbpererr2',
       'pl_orbperlim', 'pl_orbsmax', 'pl_orbsmaxerr1', 'pl_orbsmaxerr2',
       'pl_orbsmaxlim', 'pl_rade', 'pl_radeerr1', 'pl_radeerr2', 'pl_radelim',
       'pl_radj', 'pl_radjerr1', 'pl_radjerr2', 'pl_radjlim', 'pl_bmasse',
       'pl_bmasseerr1', 'pl_bmasseerr2', 'pl_bmasselim', 'pl_bmassj',
       'pl_bmassjerr1', 'pl_bmassjerr2', 'pl_bmassjlim', 'pl_bmassprov',
       'pl_orbeccen', 'pl_orbeccenerr1', 'pl_orbeccenerr2', 'pl_orbeccenlim',
       'pl_insol', 'pl_insolerr1', 'pl_insolerr2', 'pl_insollim', 'pl_eqt',
       'pl_eqterr1', 'pl_eqterr2', 'pl_eqtlim', 'ttv_flag', 'st_spectype',
       'st_teff', 'st_tefferr1', 'st_tefferr2', 'st_tefflim', 'st_rad',
       'st_raderr1', 'st_raderr2', 'st_radlim', 'st_mass', 'st_masserr1',
       'st_masserr2', 'st_masslim', 'st_met', 'st_meterr1', 'st_meterr2',
       'st_metlim', 'st_metratio', 'st_logg', 'st_loggerr1', 'st_loggerr2',
       'st_logglim', 'rastr', 'ra', 'decstr', 'dec', 'sy_dist', 'sy_disterr1',
       'sy_disterr2', 'sy_vmag', 'sy_vmagerr1', 'sy_vmagerr2', 'sy_kmag',
       'sy_kmagerr1', 'sy_kmagerr2', 'sy_gaiamag', 'sy_gaiamagerr1',
       'sy_gaiamagerr2'],
      dtype='object')

In [28]:
merge_planet_df.to_csv("merge_planet_csv")
files.download("merge_planet_csv")